services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssqldb
    volumes:
      - ./html:/var/www/html           # map content of ./html in your computer to /var/www/html of container
      - ./php_conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # map xdebug.ini into the container
      - ./php_conf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini # map error_reporting.ini into the container
  nginx:
    image: nginx:1.29                  # set the nginx version you need for your project
    ports:
      - "8000:80"                      # map your computer port to the container port
    depends_on:
      - php
    volumes:
      - ./html:/var/www/html           # map content of ./html in your computer to /var/www/html of container
      - ./nginx_conf:/etc/nginx/conf.d # map content of ./nginx-conf in your computer to /etc/nginx/conf.d of container
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest # set the mssql version you need for your project
    ports:
      - "1433:1433"                    # map your computer port to the container port
    environment:
      - ACCEPT_EULA=Y                  # set to Y if you accept the EULA
      - MSSQL_SA_PASSWORD=123456Ms     # https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy
      - MSSQL_PID=Developer            # set product key: Developer, Express, Web or Standard
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_COLLATION=Latin1_General_100_CI_AS_SC_UTF8 # https://learn.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15#utf8
      - TZ=Etc/UTC                     # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-time-zone
    volumes:
      - ./mssqldb_data/backups:/var/opt/mssql/backups # map content of ./mssqldb_data/backups in your computer
      - ./mssqldb_data/data:/var/opt/mssql/data       # map content of ./mssqldb_data/data in your computer
      - ./mssqldb_data/log:/var/opt/mssql/log         # map content of ./mssqldb_data/log in your computer
  